package com.sai.talentassessment.model;

import jakarta.persistence.*; // <-- THE FIX IS HERE
import java.time.LocalDateTime;
import lombok.Data;

/**
 * Represents a single assessment record for an athlete.
 * This entity stores the verified results of one fitness test.
 */
@Entity
@Data
public class AssessmentData {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "athlete_id")
    private AthleteProfile athlete;

    private String testName; // e.g., "Vertical Jump", "Sit-ups"
    private double resultValue; // The metric (e.g., jump height in cm, count of sit-ups)
    private String resultUnit; // "cm", "reps", "seconds"
    private LocalDateTime submissionDate;
    private String videoUrl; // URL to the stored video for verification by officials
    private boolean isVerified; // Flag set to true after on-device AI verification
    private boolean hasAnomalies; // Flag from the cheat detection module

    // Standard getters, setters, and constructors are generated by Lombok
}