package com.sai.talentassessment.model;

import jakarta.persistence.*; // <-- THE FIX IS HERE
import java.time.LocalDate;
import java.util.List;
import lombok.Data;

/**
 * Represents an athlete's profile in the database.
 * This entity stores demographic and physical information about the athlete.
 */
@Entity
@Data // Lombok annotation to generate getters, setters, etc.
public class AthleteProfile {
    @Id
    private String id; // A unique ID for the athlete, could be generated by the app
    private String name;
    private LocalDate dateOfBirth;
    private String gender;
    private String region; // e.g., state, district

    @OneToMany(mappedBy = "athlete", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<AssessmentData> assessments;

    // Standard getters, setters, and constructors are generated by Lombok
}